### ISSUE TITLE
Registration broken in 2.1.7

### ISSUE THREAD

**Issue by StephanJanosch** [bigdataviewer/SPIM_Registration#18]
2 channel Dataset, only beads and nuclei in ch 2.

Registration throws NPE
```
(Fiji Is Just) ImageJ 2.0.0-rc-28/1.49q; Java 1.6.0_24 [64-bit]; Linux 3.13.0-48-generic; 143MB of 62000MB (<1%)
 
java.lang.NullPointerException
	at spim.process.interestpointregistration.optimizationtypes.GlobalOptimizationType.getInterestPoints(GlobalOptimizationType.java:180)
	at spim.process.interestpointregistration.optimizationtypes.IndividualTimepointRegistration.assembleAllViewPairs(IndividualTimepointRegistration.java:38)
	at spim.process.interestpointregistration.optimizationtypes.GlobalOptimizationType.getAllViewPairs(GlobalOptimizationType.java:85)
	at spim.fiji.plugin.Interest_Point_Registration.setFixedTilesAndReference(Interest_Point_Registration.java:379)
	at spim.fiji.plugin.Interest_Point_Registration.register(Interest_Point_Registration.java:358)
	at spim.fiji.plugin.Interest_Point_Registration.run(Interest_Point_Registration.java:103)
	at ij.IJ.runUserPlugIn(IJ.java:199)
	at ij.IJ.runPlugIn(IJ.java:163)
	at ij.Executer.runCommand(Executer.java:131)
	at ij.Executer.run(Executer.java:61)
	at java.lang.Thread.run(Thread.java:662)
```
![screenshot from 2015-04-08 10 53 24](https://cloud.githubusercontent.com/assets/11651596/7041958/359063c0-ddde-11e4-9c59-a201e1925862.png)
![screenshot from 2015-04-08 10 55 12](https://cloud.githubusercontent.com/assets/11651596/7041963/45abe978-ddde-11e4-9002-9986c7101f4c.png)
![screenshot from 2015-04-08 10 55 36](https://cloud.githubusercontent.com/assets/11651596/7041964/48175d1e-ddde-11e4-975c-656ab8549e82.png)
![screenshot from 2015-04-08 10 55 57](https://cloud.githubusercontent.com/assets/11651596/7041965/49d76c84-ddde-11e4-93f8-cc73db56c071.png)
![screenshot from 2015-04-08 10 56 42](https://cloud.githubusercontent.com/assets/11651596/7041967/4b3202f6-ddde-11e4-904d-460029cc8eed.png)

**Comment by StephanPreibisch** [comment]
Fixed with commits https://github.com/bigdataviewer/SPIM_Registration/commit/fd249a909dbe6943ec895ae97cc94fddeedacb28 and https://github.com/bigdataviewer/SPIM_Registration/commit/8dd2c955c2112ac0d8ce14757f06d5a5346b497a

Thanks for reporting!!
