### ISSUE TITLE
Exlorer Bug

### ISSUE THREAD

**Issue by StephanJanosch** [bigdataviewer/SPIM_Registration#19]
Dataset, 2 channels, 1st channel no detections

2nd channel selected, context menu, register
```
Exception in thread "Thread-591" java.lang.ArrayIndexOutOfBoundsException: 1
	at spim.fiji.plugin.Interest_Point_Registration.register(Interest_Point_Registration.java:187)
	at spim.fiji.plugin.Interest_Point_Registration.register(Interest_Point_Registration.java:115)
	at spim.fiji.spimdata.explorer.popup.RegisterInterestPointsPopup$MyActionListener$1.run(RegisterInterestPointsPopup.java:55)
	at java.lang.Thread.run(Thread.java:662)
```

**Comment by StephanPreibisch** [comment]
Fixed with commit https://github.com/bigdataviewer/SPIM_Registration/commit/a9d55a9653440f72d32cf75f43322077d6046c45.

Thanks again @StephanJanosch !
