### ISSUE TITLE
Select multiple interest points in explorer and delete them -> Exception

### ISSUE THREAD

**Issue by StephanJanosch** [bigdataviewer/SPIM_Registration#24]
```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at spim.fiji.spimdata.explorer.interestpoint.InterestPointTableModel.label(InterestPointTableModel.java:93)
	at spim.fiji.spimdata.explorer.interestpoint.InterestPointExplorerPanel.delete(InterestPointExplorerPanel.java:128)
	at spim.fiji.spimdata.explorer.interestpoint.InterestPointExplorerPanel$1.actionPerformed(InterestPointExplorerPanel.java:242)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
![screen shot 2015-04-09 at 10 34 33](https://cloud.githubusercontent.com/assets/11651596/7063104/0e8737c4-dea4-11e4-8d62-ee70dd44fd41.png)

**Comment by ctrueden** [comment]
Ah, the classic "delete multiple rows from a table" bug. I bet it's even worse if you select, say, indices 1 and 3 from a list of five items. Probably the wrong item 3 gets deleted.

Maybe this patch fixes it?
```diff
diff --git a/src/main/java/spim/fiji/spimdata/explorer/interestpoint/InterestPointExplorerPanel.java b/src/main/java/spim/fiji/spimdata/explorer/interestpoint/InterestPointExplorerPanel.java
index dddce98..e9ae97a 100644
--- a/src/main/java/spim/fiji/spimdata/explorer/interestpoint/InterestPointExplorerPanel.java
+++ b/src/main/java/spim/fiji/spimdata/explorer/interestpoint/InterestPointExplorerPanel.java
@@ -123,8 +123,9 @@ public class InterestPointExplorerPanel extends JPanel

                final ViewInterestPoints vip = tableModel.getViewInterestPoints();

-               for ( final int row : selectedRows )
+               for ( int rowIndex = selectedRows.length - 1; rowIndex >= 0; rowIndex--)
                {
+                       final int row = selectedRows[rowIndex];
                        final String label = InterestPointTableModel.label( vip, vd, row );

                        IOFunctions.println( "Removing label '' for timepoint_id " + vd.getTimePointId() + " viewsetup_id " + vd.getViewSetupId() + " -- Parsing through all correspondences to remove any links to this interest point list." );
```
I didn't test it, though.

**Comment by StephanPreibisch** [comment]
Yes, it does, thanks so much @ctrueden.

Fixed with commit https://github.com/bigdataviewer/SPIM_Registration/commit/55d678ac969d36cb98cbdf07b83c661152269e83

**Comment by ctrueden** [comment]
:+1:
