### ISSUE TITLE
NPE 

### ISSUE THREAD

**Issue by StephanJanosch** [bigdataviewer/SPIM_Registration#28]
Dataset at: http://idisk.mpi-cbg.de/~janosch/issue28.zip

It works, if I only select one channel. It fails, if I select both channels.
```
Exception in thread "Thread-16" java.lang.NullPointerException
	at spim.fiji.plugin.interestpointregistration.InterestPointRegistration.register(InterestPointRegistration.java:175)
	at spim.fiji.plugin.Interest_Point_Registration.register(Interest_Point_Registration.java:359)
	at spim.fiji.plugin.Interest_Point_Registration.register(Interest_Point_Registration.java:115)
	at spim.fiji.spimdata.explorer.popup.RegisterInterestPointsPopup$MyActionListener$1.run(RegisterInterestPointsPopup.java:55)
	at java.lang.Thread.run(Thread.java:745)
```

![screen shot 2015-04-14 at 09 54 13](https://cloud.githubusercontent.com/assets/11651596/7132726/48eb9e3c-e28c-11e4-93fd-7e4a934a2221.png)
![screen shot 2015-04-14 at 09 54 24](https://cloud.githubusercontent.com/assets/11651596/7132733/507e0e14-e28c-11e4-8b26-48cf6b60c034.png)
![screen shot 2015-04-14 at 10 09 56](https://cloud.githubusercontent.com/assets/11651596/7132964/72e379a6-e28e-11e4-9702-146242ab2a4b.png)

**Comment by StephanPreibisch** [comment]
Fixed with this commit: https://github.com/bigdataviewer/SPIM_Registration/commit/a8b03eab6d3f10bb8229b975caffa4188e52919d

By the way, the list of detection is empty ... under normal circumstances this would not happen
