### ISSUE TITLE
Silent failure when choosing "Save as new XML Project (HDF5)" on float type images

### ISSUE THREAD

**Issue by nicost** [bigdataviewer/SPIM_Registration#33]
When choosing the output option "Save as new XML Project (HDF5)" in the "image Fusion/Deconvolution" section, and the data is of type float (as it always is after deconvolution), saving data fails silently with an UnsupportedOperationException (see stack trace below as an example).  One solution appears to be to convert the data to unsigned short (however, since I am not sure what scaling to use to do so, I rather file this bug report than create a pull request).

Exception in thread "Thread-8" java.lang.UnsupportedOperationException: only UnsignedShortType supported.
	at spim.process.fusion.export.ExportSpimData2HDF5.exportImage(ExportSpimData2HDF5.java:206)
	at spim.process.fusion.export.ExportSpimData2HDF5.exportImage(ExportSpimData2HDF5.java:197)
	at spim.process.fusion.weightedavg.ProcessIndependent.fuseStack(ProcessIndependent.java:133)
	at spim.process.fusion.weightedavg.WeightedAverageFusion.fuseData(WeightedAverageFusion.java:93)
	at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:165)
	at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:87)
	at spim.fiji.spimdata.explorer.popup.FusionPopup$MyActionListener$1.run(FusionPopup.java:57)
	at java.lang.Thread.run(Thread.java:695)

**Comment by StephanPreibisch** [comment]
Hi @nicost, @tpietzsch is working on support of 32-bit for his HDF5 format ... until then we should maybe ask the user. I will try to do this next week!

**Comment by StephanPreibisch** [comment]
Fixed with commit https://github.com/bigdataviewer/SPIM_Registration/commit/d0d1a3a8d4eda4617c6977165856da77bac69f7f
