### ISSUE TITLE
Multiview-Deconvolution NullPointerException

### ISSUE THREAD

**Issue by tibuch** [bigdataviewer/SPIM_Registration#51]
I tried a multiview-deconvolution and got this exception:

```java
java.lang.NullPointerException
	at spim.fiji.spimdata.interestpoints.InterestPointList.loadInterestPoints(InterestPointList.java:189)
	at spim.process.fusion.deconvolution.EfficientBayesianBased.assembleAvailableCorrespondences(EfficientBayesianBased.java:1090)
	at spim.process.fusion.deconvolution.EfficientBayesianBased.getPSF(EfficientBayesianBased.java:614)
	at spim.process.fusion.deconvolution.EfficientBayesianBased.queryParameters(EfficientBayesianBased.java:252)
	at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:160)
	at spim.fiji.plugin.Image_Fusion.run(Image_Fusion.java:76)
	at ij.IJ.runUserPlugIn(IJ.java:199)
	at ij.IJ.runPlugIn(IJ.java:163)
	at ij.Executer.runCommand(Executer.java:131)
	at ij.Executer.run(Executer.java:64)
	at java.lang.Thread.run(Thread.java:662)
```

I use "Fiji continuous release" on Windows 7 64bit.

**Comment by StephanPreibisch** [comment]
Hi @tibuch, can you please provide the ImageJ log window output as well? Thanks a lot ...

**Comment by tibuch** [comment]
ImageJ log window:
```
Using spimdata version: 0.9-revision
Using spimreconstruction version: 2.3.8
angles selected: 0, 90
channels selected: 0
illuminations selected: 0
Timepoints selected: 0
Fri May 22 10:07:17 CEST 2015: Estimating Bounding Box for Fusion. If size of images is not known (they were never opened before), some of them need to be opened once to determine their size.
Min: (130, 192, 147)
Max: (796, 892, 733)
Fri May 22 10:08:56 CEST 2015: Estimating Bounding Box for Fusion. If size of images is not known (they were never opened before), some of them need to be opened once to determine their size.
```

**Comment by StephanPreibisch** [comment]
Hi @tibuch, I cannot figure it out from that what goes wrong ... can you please send me an email containing the XML and the interestpoints directory zipped together with how exactly you call the plugin?

**Comment by tibuch** [comment]
Hi @StephanPreibisch, I am at another system right now. And on this system i do not have any problems.

If I run into this again, I will collect as much as possible and write you an email. 

Guess we can close this issue for now.
