### ISSUE TITLE
Resaving first angle as all angles.

### ISSUE THREAD

**Issue by gabrieldavisjones** [bigdataviewer/SPIM_Registration#72]
We are having some trouble with the resave function in Multiview Reconstruction.
I have a dataset acquired with our OpenSPIM setup which consists of one time point and 12 angles (each angle being 2.6GB, saved as ome.tiff). We're running on a Dell R820 rackmount server running Ubuntu(512GB RAM, 64 core [~2.4GHz]). The two issues we're encountering are:

1. The HDF5 file simply resaves the first angle 12 times, i.e. if I select angle 7 to open then angle 1 shows up again. The same issue is seen when resaving as tifs instead. 
2. It's very slow, taking approximately 14 hours to resave these files.

The list of files is:
spim_TL01_Angle0.ome.tiff
spim_TL01_Angle1.ome.tiff
spim_TL01_Angle2.ome.tiff
spim_TL01_Angle3.ome.tiff
spim_TL01_Angle4.ome.tiff
spim_TL01_Angle5.ome.tiff
spim_TL01_Angle6.ome.tiff
spim_TL01_Angle7.ome.tiff
spim_TL01_Angle8.ome.tiff
spim_TL01_Angle9.ome.tiff
spim_TL01_Angle10.ome.tiff
spim_TL01_Angle11.ome.tiff

I have also provided the dataset.xml files here: https://www.dropbox.com/sh/nuggy9mqqzd9gne/AADsZqswV_02IyhcD9DV_E5ha?dl=0

**Comment by StephanPreibisch** [comment]
Could you also provide the log of the Fiji window please?

**Comment by gabrieldavisjones** [comment]
Unfortunately, I've already closed the Fiji log window. I could resave the images again to get it back?

**Comment by StephanPreibisch** [comment]
sorry, yes, that would be great. Could you first segment some beads or so in each angle and send me the log for that?

**Comment by gabrieldavisjones** [comment]
I have uploaded the log.txt for the resave to the aforementioned DropBox folder. Unfortunately, we haven't been using beads, as we have been imaging neurons using the 3DISCO method, which doesn't allow for bead embedding. I can image some beads in the coming days and send you the log for that acquisition?

**Comment by StephanPreibisch** [comment]
Hi, it seems to work just fine ... what exactly is the problem? How do you look at the images?

**Comment by gabrieldavisjones** [comment]
When I open the dataset.h5 file with Big Data Viewer, I am only able to see one view. It's the same view for every angle. Even when I choose to hide all angles except for one, it's still showing the first angle, as though it has saved the first angle in place of all the other angles.

I have uploaded the dataset file to the dropbox folder I provided above. It is 14GB, though...

As a side note, other users seem to be having troubles with the ome.tiff/bio-formats file types with their SPIM data (http://openspim.org/pipermail/openspim/2015-July/000782.html) Perhaps it's related?

**Comment by StephanPreibisch** [comment]
Once you define the dataset (without HDF5 conversion), can you try to just display a few angles as 32bit and tell me if that works?

**Comment by StephanPreibisch** [comment]
It sounds like it is related. Can you try to use the ImageJ imgloader when you define the dataset, not LOCI?

**Comment by gabrieldavisjones** [comment]
Defining the dataset with imgloader works.
If I try displaying the data the Multiview Construction, I get the following exception:
(Fiji Is Just) ImageJ 2.0.0-rc-34/1.50a; Java 1.6.0_24 [64-bit]; Linux 3.10.0-229.4.2.el7.x86_64; 2674MB of 383190MB (<1%)
 
java.lang.NoClassDefFoundError: Could not initialize class org.jdom2.input.sax.XMLReaders
	at org.jdom2.input.SAXBuilder.<init>(SAXBuilder.java:338)
	at org.jdom2.input.SAXBuilder.<init>(SAXBuilder.java:221)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:48)
	at spim.fiji.plugin.queryXML.GenericLoadParseQueryXML.parseXML(GenericLoadParseQueryXML.java:787)
	at spim.fiji.plugin.queryXML.GenericLoadParseQueryXML.tryParsing(GenericLoadParseQueryXML.java:671)
	at spim.fiji.plugin.queryXML.GenericLoadParseQueryXML.queryXML(GenericLoadParseQueryXML.java:230)
	at spim.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:83)
	at spim.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:74)
	at spim.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:31)
	at spim.fiji.plugin.Display_View.run(Display_View.java:45)
	at ij.IJ.runUserPlugIn(IJ.java:212)
	at ij.IJ.runPlugIn(IJ.java:176)
	at ij.Executer.runCommand(Executer.java:132)
	at ij.Executer.run(Executer.java:65)
	at java.lang.Thread.run(Thread.java:662)

**Comment by StephanPreibisch** [comment]
With which ImgLoader, the ImageJ Imgloader? Anyhow, I cannot confirm this error ... can you please update Fiji and try again?

**Comment by gabrieldavisjones** [comment]
I tried defining the dataset with the ImageJ Opener however because their ome.tiff files, I get the Bio-Formats Import Options dialog. If I uncheck all boxes, I get the "Bioformats Series Options" where I can select which stacks I want to include. Regardless of whether I choose one stack or all of them, it simply hangs on "import preparations complete" and never defines the dataset.

**Comment by gabrieldavisjones** [comment]
Sorry, I forgot to mention that if I select all series in the Bioformats Series Options, it will open the first stack/angle and then fail with:

Loading calibration for: /data/users/gabrielj/data/Cerebellum/spim_TL01_Angle0.ome.tiff
Could not open file: '/data/users/gabrielj/data/Cerebellum/spim_TL01_Angle0.ome.tiff'
Defining multi-view dataset failed.

**Comment by StephanPreibisch** [comment]
Hi @gabrieldavisjones,

this seems to be all wrong somehow. Can you please post screenshots here of how you define the dataset? There should never be any bioformats dialog ... 

Thanks so much,
Stephan
