### ISSUE TITLE
NoClassDefFoundError when registering interest points

### ISSUE THREAD

**Issue by emmenlau** [bigdataviewer/SPIM_Registration#76]
When I try to register interest points using ICP with a Fixed first Tile and an Affine model with Regularization, I get a NoClassDefFoundError exception:

```
Exception in thread "Thread-759" java.lang.NoClassDefFoundError: javax/media/j3d/Transform3D
	at spim.process.interestpointregistration.GlobalOpt.getTransform3D(GlobalOpt.java:166)
	at spim.process.interestpointregistration.GlobalOpt.getScaling(GlobalOpt.java:153)
	at spim.process.interestpointregistration.GlobalOpt.compute(GlobalOpt.java:115)
	at spim.process.interestpointregistration.optimizationtypes.GlobalOptimizationSubset.computeGlobalOpt(GlobalOptimizationSubset.java:68)
	at spim.fiji.plugin.interestpointregistration.InterestPointRegistration.runGlobalOpt(InterestPointRegistration.java:104)
	at spim.fiji.plugin.interestpointregistration.InterestPointRegistration.register(InterestPointRegistration.java:205)
	at spim.fiji.plugin.Interest_Point_Registration.register(Interest_Point_Registration.java:388)
	at spim.fiji.plugin.Interest_Point_Registration.register(Interest_Point_Registration.java:118)
	at spim.fiji.spimdata.explorer.popup.RegisterInterestPointsPopup$MyActionListener$1.run(RegisterInterestPointsPopup.java:55)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.media.j3d.Transform3D
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 10 more
```

**Comment by StephanPreibisch** [comment]
This means java3d is missing ... do you run it from within eclipse or Fiji? I would guess eclipse and the class path for java3d is not set

**Comment by emmenlau** [comment]
I ran this from Fiji, no Eclipse installed (its a Windows box with no Admin permissions). Should I manually add java3d jar file to Fiji? Is Eclipse recommended?

**Comment by StephanPreibisch** [comment]
please try the imagej 3d viewer if it works

**Comment by StephanPreibisch** [comment]
no, it really just means that Java3D is missing. that should not happen in Fiji, in eclipse it is likely though

**Comment by emmenlau** [comment]
BigDataViewer worked, on at least one of the datasets. I tried only on one dataset, and only after a restart of Fiji, but without any changes to the classpath. Does that help?

**Comment by StephanPreibisch** [comment]
no, the ImageJ3D viewer (Plugins > 3D Viewer), not the bigdataviewer. It also uses Java3D and should crash if that is the problem.

**Comment by emmenlau** [comment]
I understand! So when I tried to start Plugins > 3D Viewer, it auto-installed new jar's, probably the missing ones. I will close the issue for now, and re-open it in case it persists after Fiji restart.

**Comment by StephanPreibisch** [comment]
That is interesting information, thanks. I was not aware that Java3D is not installed by default.
