### ISSUE TITLE
Java error after trying to detect interest points for registration, or opening an xml file

### ISSUE THREAD

**Issue by javaworms** [bigdataviewer/SPIM_Registration#85]
I am able to define a new dataset and bring up the ViewSetup Explorer, but once I try to detect interest points for registration, I get the following error:

java.lang.ExceptionInInitializerError
    at org.jdom2.input.SAXBuilder.<init>(SAXBuilder.java:338)
    at org.jdom2.input.SAXBuilder.<init>(SAXBuilder.java:221)
    at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:48)
    at spim.fiji.plugin.queryXML.GenericLoadParseQueryXML.parseXML(GenericLoadParseQueryXML.java:787)
    at spim.fiji.plugin.queryXML.GenericLoadParseQueryXML.tryParsing(GenericLoadParseQueryXML.java:671)
    at spim.fiji.plugin.queryXML.GenericLoadParseQueryXML.queryXML(GenericLoadParseQueryXML.java:230)
    at spim.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:83)
    at spim.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:74)
    at spim.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:31)
    at spim.fiji.plugin.Interest_Point_Detection.run(Interest_Point_Detection.java:64)
    at ij.IJ.runUserPlugIn(IJ.java:212)
    at ij.IJ.runPlugIn(IJ.java:176)
    at ij.Executer.runCommand(Executer.java:132)
    at ij.Executer.run(Executer.java:65)
    at java.lang.Thread.run(Thread.java:662)
Caused by: org.apache.xerces.xni.parser.XMLConfigurationException: http://apache.org/xml/features/allow-java-encodings
    at org.apache.xerces.impl.xs.XMLSchemaLoader.getFeature(Unknown Source)
    at org.apache.xerces.jaxp.validation.XMLSchemaFactory.propagateFeatures(Unknown Source)
    at org.apache.xerces.jaxp.validation.XMLSchemaFactory.newSchema(Unknown Source)
    at org.jdom2.input.sax.XMLReaders.<init>(XMLReaders.java:123)
    at org.jdom2.input.sax.XMLReaders.<clinit>(XMLReaders.java:95)
    ... 15 more

Also, I am unable to open any dataset.xml file - if I want to load a dataset, I have to define it all over again. The error I get when I try to open an xml file is:

Exception occurred during event dispatching:
java.lang.ExceptionInInitializerError
	at org.jdom2.input.SAXBuilder.<init>(SAXBuilder.java:338)
	at org.jdom2.input.SAXBuilder.<init>(SAXBuilder.java:221)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:48)
	at spim.fiji.plugin.queryXML.GenericLoadParseQueryXML.parseXML(GenericLoadParseQueryXML.java:787)
	at spim.fiji.plugin.queryXML.GenericLoadParseQueryXML.tryParsing(GenericLoadParseQueryXML.java:671)
	at spim.fiji.plugin.queryXML.GenericLoadParseQueryXML$2.textValueChanged(GenericLoadParseQueryXML.java:805)
	at java.awt.AWTEventMulticaster.textValueChanged(AWTEventMulticaster.java:451)
	at java.awt.TextComponent.processTextEvent(TextComponent.java:687)
	at java.awt.TextComponent.processEvent(TextComponent.java:656)
	at java.awt.TextField.processEvent(TextField.java:565)
	at java.awt.Component.dispatchEventImpl(Component.java:4652)
	at java.awt.Component.dispatchEvent(Component.java:4482)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:644)
	at java.awt.EventQueue.access$000(EventQueue.java:85)
	at java.awt.EventQueue$1.run(EventQueue.java:603)
	at java.awt.EventQueue$1.run(EventQueue.java:601)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
	at java.awt.EventQueue$2.run(EventQueue.java:617)
	at java.awt.EventQueue$2.run(EventQueue.java:615)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:614)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:178)
	at java.awt.Dialog$1.run(Dialog.java:1046)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:642)
	at java.awt.EventQueue.access$000(EventQueue.java:85)
	at java.awt.EventQueue$1.run(EventQueue.java:603)
	at java.awt.EventQueue$1.run(EventQueue.java:601)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
	at java.awt.EventQueue$2.run(EventQueue.java:617)
	at java.awt.EventQueue$2.run(EventQueue.java:615)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:614)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: org.apache.xerces.xni.parser.XMLConfigurationException: http://apache.org/xml/features/allow-java-encodings
	at org.apache.xerces.impl.xs.XMLSchemaLoader.getFeature(Unknown Source)
	at org.apache.xerces.jaxp.validation.XMLSchemaFactory.propagateFeatures(Unknown Source)
	at org.apache.xerces.jaxp.validation.XMLSchemaFactory.newSchema(Unknown Source)
	at org.jdom2.input.sax.XMLReaders.<init>(XMLReaders.java:123)
	at org.jdom2.input.sax.XMLReaders.<clinit>(XMLReaders.java:95)
	... 47 more

I had been able to register and view saved xml files previously - I have a fused and deconvolved stack of beads from September 10. I think maybe one of the latest updates broke something? Also, I'm on linux, and haven't been able to test it on another type of OS. Any help would be much appreciated.

**Comment by StephanPreibisch** [comment]
Hi @tpietzsch, did you update spimdata already? Might this be related? I am traveling and will only be able to check it out on Monday night.

Thanks, Stephan

**Comment by tpietzsch** [comment]
@StephanPreibisch No, I didn't push the new jars to the updater yet. This is not related.
The exception is thrown from within JDK, when initializing XML somehow in this code in jdom2:
```
					SchemaFactory sfac = SchemaFactory.
							newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
					Schema schema = sfac.newSchema();
					fac.setSchema(schema);
					val = true;
```
So nothing to do with SPIM_Registration or spim_data. Looks more like a problem with the general java or fiji installation.
@javaworms is your Fiji up-to-date? Which update sites are enabled? Can you verify the problem with a newly installed Fiji? Which java version are you using?

**Comment by axtimwalde** [comment]
If I understand correctly, this is related to https://github.com/scijava/pom-scijava/pull/19 which is already merged.  I have not tested yet whether it is already available through the Fiji updater but would guess so.

**Comment by ctrueden** [comment]
Nope, I didn't push the new jdom to the update site yet.

**Comment by tpietzsch** [comment]
@axtimwalde @ctrueden So, does this mean that this problem should go away once the new JDOM is pushed to the updater?

**Comment by StephanPreibisch** [comment]
Thanks @tpietzsch @axtimwalde @ctrueden!!

**Comment by javaworms** [comment]
Sounds like the problem has been found. Thanks everyone for the help. When can I expect the fix to be pushed to the fiji updater?

**Comment by ctrueden** [comment]
@javaworms The fix was pushed this past Friday. Sorry for the delay in notification.

Could someone please confirm that this problem is now solved in the latest Fiji?

**Comment by javaworms** [comment]
It's working for me now, thank you very much.

**Comment by ctrueden** [comment]
Awesome, thanks for the quick followup.
