### ISSUE TITLE
posible bug

### ISSUE THREAD

**Issue by ccortescampos** [bigdataviewer/SPIM_Registration#9]
Hi!!,
I'm trying process a big data (tiff), 3 channels with 6 angles each one (4.57GB each angle). But  in detect interest points for registration I got the following exception and the plugin stop. 

(Fiji Is Just) ImageJ 2.0.0-rc-23/1.49m; Java 1.6.0_24 [64-bit]; Linux 3.13.0-43-generic; 17848MB of 56383MB (31%)
 
java.lang.NegativeArraySizeException
at mpicbg.imglib.container.basictypecontainer.array.FloatArray.<init>(FloatArray.java:54)
at mpicbg.imglib.container.array.ArrayContainerFactory.createFloatInstance(ArrayContainerFactory.java:147)
at mpicbg.imglib.type.numeric.real.FloatType.createSuitableDirectAccessContainer(FloatType.java:83)
at mpicbg.imglib.container.DirectAccessContainerFactory.createContainer(DirectAccessContainerFactory.java:69)
at mpicbg.imglib.container.DirectAccessContainerFactory.createContainer(DirectAccessContainerFactory.java:55)
at mpicbg.imglib.image.Image.<init>(Image.java:113)
at mpicbg.imglib.image.Image.<init>(Image.java:136)
at mpicbg.imglib.image.ImageFactory.createImage(ImageFactory.java:69)
at mpicbg.imglib.image.ImageFactory.createImage(ImageFactory.java:72)
at mpicbg.spim.segmentation.InteractiveDoG.convertToFloat(InteractiveDoG.java:386)
at mpicbg.spim.segmentation.InteractiveDoG.run(InteractiveDoG.java:180)
at spim.fiji.plugin.interestpointdetection.DifferenceOfGaussian.setInteractiveValues(DifferenceOfGaussian.java:270)
at spim.fiji.plugin.interestpointdetection.DifferenceOf.queryParameters(DifferenceOf.java:206)
at spim.fiji.plugin.Interest_Point_Detection.run(Interest_Point_Detection.java:152)
at ij.IJ.runUserPlugIn(IJ.java:202)
at ij.IJ.runPlugIn(IJ.java:166)
at ij.Executer.runCommand(Executer.java:131)
at ij.Executer.run(Executer.java:64)
at java.lang.Thread.run(Thread.java:662)

I got the same exception if I select CellImg.

**Comment by StephanPreibisch** [comment]
Hi @ccortescampos,

I will try to fix this issue. In the meantime it should work to select "Downsampling" (maybe 2x/1x or 4x/1x) in the Segmentation Dialog. I anyways highly suggest that for datasets of this size.

Thanks so much for reporting!

**Comment by StephanPreibisch** [comment]
This was fixed, should work now ...
